# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ensure-encoding"
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra"]
  s.date = "2011-12-21"
  s.description = "Ensure the character encoding in Strings coming from untrusted sources."
  s.email = "manfred@fngtps.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "ensure-encoding.gemspec",
    "lib/ensure/encoding.rb",
    "lib/ensure.rb"
  ]
  s.homepage = " "
  s.licenses = [" "]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.3.5"
  s.summary = "Ensure the character encoding in Strings coming from untrusted sources."

end
